### PR TITLE
Ft signup 175795738

### PR DESCRIPTION
**Pull request by uwadonat**
#### What does this PR do?
- this pull request design all user interface of freeMentors using HTML and CSS.
#### Description of Task to be completed?
- user ,mentor and admin can have sign up, sign views and interact with it. 
#### How should this be manually tested?
- clone it and open user interface
#### Any background context you want to provide?
- I tried to design UI, but not professionally I need your guidance to make it better
#### What are the relevant pivotal tracker stories?
- [#175795738](https://www.pivotaltracker.com/story/show/175795738)
- #175796058

- 175795751
- 175795730
- 175795763
- 175795763
#### Screenshots (if appropriate)
image
image
image

#### Questions:
N/A

### CODE REVIEW

**Review by hakoemmy — COMMENTED** [review]
@uwadonat Good job. 

Kindly improve how you write the pull request description like for example.

Where there is # symbol, put there - to have a well a dot for every list.  Lookt this example below.

This **#this pull request design all user interface of freeMentors using HTML and CSS** Make it **- This pull request design all user interface of freeMentors using HTML and CSS**

**Comment by uwadonat** [comment]
Wooo! It looks good. then what about the content?

**Comment by hakoemmy** [comment]
> Wooo! It looks good. then what about the content?

> @uwadonat  FOr content side. You can even try using dummy content from well-known sites like https://www.lipsum.com/ to generate free content for you no ned of focusing on the content itself, just focus on utilizing HTML, CSS, and javascript skills

**Comment by hakoemmy** [comment]
> @uwadonat Good job.
> 
> Kindly improve how you write the pull request description like for example.
> 
> Where there is # symbol, put there - to have a well a dot for every list. Lookt this example below.
> 
> This **#this pull request design all user interface of freeMentors using HTML and CSS** Make it **- This pull request design all user interface of freeMentors using HTML and CSS**

> @uwadonat You have made an improvement on how you write pull request description but you forgot an important issue. Kindly make Pivotal tracker stories as links for example: [#175795738](https://www.pivotaltracker.com/story/show/175795738) 

Format to follow. [#PivotalTrackerId](Link-to-that-story).

Happy coding!

**Comment by uwadonat** [comment]
hi guhindura #pivottracketId ikaba link ko bincanze ra. nureba hejuru urabona ko nabigerageje ariko birakomeza bikibera ibisanzwe.
haha!!! sorry.

**Comment by hakoemmy** [comment]
> hi guhindura #pivottracketId ikaba link ko bincanze ra. nureba hejuru urabona ko nabigerageje ariko birakomeza bikibera ibisanzwe.
> haha!!! sorry.

> Hi kindly learn from what I have done, just updated the first link. Please see the attached screenshot to have a clue
In below screenshot you see, start by Id and then the link
lern from this

**Pull request merged**
